apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplace-example
  namespace: argocd
spec:
  destination:
    namespace: crossplace-example
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployments/terraform-cloud-agents/base
    repoURL: git@github.com:turo/terraform-cloud-agents-deployments
    targetRevision: HEAD
