apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmChartInflationGenerator:
- chartName: crossplane-stable/crossplane
  chartRepoUrl: https://charts.crossplane.io/stable
  releaseName: crossplane
  releaseNamespace: crossplane-system

resources:
  - providers.yaml