apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-example
  namespace: argocd
spec:
  destination:
    namespace: crossplane-example
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications
    repoURL: https://github.com/yohanb/crossplane-example
    targetRevision: HEAD
